### ISSUE TITLE
How can the results for songs be so different ?

### ISSUE THREAD

**Issue by asterixlb** [intel/openvino-plugins-ai-audacity#48] opened 2024-02-11 10:26 UTC
I separated different songs with the same installation. There's an unbelievable difference. One is almost perfect, for the other ones the vocals have hardly diminushed in the "others" stem and almost zero in the "vocals" stem. How come ?

**Comment by RyanMetcalfeInt8** [comment] 2024-02-12 01:14
Hmm, it's hard to say exactly why. It may come down to what the model (demucs v4 from Meta) was trained for. If you're willing to share the track / snipper that didn't work well for you, I can at least double check that I am getting the same result as you. But it's up to you of course.

**Comment by asterixlb** [comment] 2024-02-12 13:51
The Proclaimers - I'm Gonna Be (500 Miles)AudSplTr-5.wav
<https://drive.google.com/file/d/1fEc8xCPMMXbY_0ezUmiYw_A4Ukl-n6eQ/view?usp=drive_web>
 Will Tura - El bandido.wav
<https://drive.google.com/file/d/1OfYU3JGMYUvvRsrTIDcV-z_xDGHfPZjr/view?usp=drive_web>
Hello,

Here are the wav-files after processing.

Thx for your reaction.

Op ma 12 feb 2024 om 02:14 schreef Ryan Metcalfe ***@***.***>:

**Comment by asterixlb** [comment] 2024-02-12 17:40
And these are the projects.
 The Proclaimers - I'm Gonna Be (500 Miles)AudSplTr-5.aup3
<https://drive.google.com/file/d/18Q7iOqlIu4R7WYFAmAL5Ki7ozlmzxwmE/view?usp=drive_web>
 Will Tura - El bandido.aup3
<https://drive.google.com/file/d/1wprJYqb1oya81y-46_PLkgXzamup3Hsm/view?usp=drive_web>

Op ma 12 feb 2024 om 02:14 schreef Ryan Metcalfe ***@***.***>:

**Comment by RyanMetcalfeInt8** [comment] 2024-02-14 01:07
Hi @asterixlb,

Sorry for the delay in taking a look. Would you mind setting the permissions of those files to public? Looks like I don't have access.

Thanks,
Ryan

**Comment by asterixlb** [comment] 2024-02-14 09:53
Hello,

permissions should be ok now.

Op wo 14 feb 2024 om 02:08 schreef Ryan Metcalfe ***@***.***>:

**Comment by asterixlb** [comment] 2024-02-14 15:21
Can I send them by WeTransfer ?

Op wo 14 feb 2024 om 14:10 schreef Ryan Metcalfe ***@***.***>:

**Comment by asterixlb** [comment] 2024-02-14 15:26
https://drive.google.com/file/d/1KCrkA6J9mitkrpc3CHEzb8YruP0PqXYv/view?usp=sharing
https://drive.google.com/file/d/1n-DqfNrPrW-8Vh1lEADDNmZscQmYSltp/view?usp=drive_link
https://drive.google.com/file/d/1_eh0co8G14oDVmtlxMIwkDSlLrqQtqkY/view?usp=drive_link
https://drive.google.com/file/d/1z23sW5w3IsXmiEIV2PxkID13BaYHm5Nw/view?usp=sharing

---------- Forwarded message ---------
Van: Luc BOSSU ***@***.***>
Date: wo 14 feb 2024 om 16:20
Subject: Re: [intel/openvino-plugins-ai-audacity] How can the results for
songs be so different ? (Issue #48)
To: intel/openvino-plugins-ai-audacity <
***@***.***>


Can I send them by WeTransfer ?

Op wo 14 feb 2024 om 14:10 schreef Ryan Metcalfe ***@***.***>:

**Comment by RyanMetcalfeInt8** [comment] 2024-02-14 15:29
I'm able to access them now. Thanks, I'll take a look.

**Comment by RyanMetcalfeInt8** [comment] 2024-02-14 20:04
Hi @asterixlb,

Sorry, maybe I didn't understand what you were sending. Looks like you sent some output from music separation. Would you mind sharing the input, so that I can double check that I am getting the same output results as you?

BR, Ryan

**Comment by RyanMetcalfeInt8** [comment] 2024-03-08 13:16
Hi @asterixlb,

I can still take a look if you're interested, otherwise I'll close this one.

Thanks,
Ryan

**Comment by asterixlb** [comment] 2024-03-13 10:51
Hello,

Here are the links to the originals :


https://drive.google.com/file/d/1dzpO8omMoF2N9jYxhrynjMWoGNFnYAoE/view?usp=sharing

https://drive.google.com/file/d/1uAf6zYKDUCsRM_WgOPWmJEyuWE33B0QJ/view?usp=sharing

Op vr 8 mrt 2024 om 14:17 schreef Ryan Metcalfe ***@***.***>:

**Comment by Elshara** [comment] 2024-03-25 17:31
Is the issue that you can't separate vocals consistently?

**Comment by asterixlb** [comment] 2024-03-25 18:41
The result is very different from song to song.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Elshara Silverheart ***@***.***> Datum: 25/03/2024  18:31  (GMT+01:00) Aan: intel/openvino-plugins-ai-audacity ***@***.***> Cc: asterixlb ***@***.***>, Mention ***@***.***> Onderwerp: Re: [intel/openvino-plugins-ai-audacity] How can the results for songs be so different ? (Issue #48) 
Is the issue that you can't separate vocals consistently?

**Comment by RyanMetcalfeInt8** [comment] 2024-03-26 00:07
Hi @asterixlb,

Sorry for the delay in trying this out. I tried 'El Bandido' on my side, and I was able to produce something reasonable (just a screenshot of the waveform):
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/e07ad20e-b701-42f0-a78b-5a7e1dae5a48)

vs. yours, which seems to be mostly noise:
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/159beaf1-0476-43e8-998a-99ad2ff08b2a)

I'm suspecting that perhaps you are experiencing this issue: #1 (which I think this is what @Elshara was hinting at)

One way to find out is, try to delete your ```%appdata%\audacity\openvino-model-cache``` folder (you can copy and paste that path into Windows explorer), and try running music sep on that El Bandido track again. If it's the same issue, the first time you run music separation after deleting that folder, you will get good output. The next time you run (no matter what track you use), it will produce bad results.

Thanks,
Ryan

**Comment by asterixlb** [comment] 2024-03-31 05:59
Hello Ryan, I tried what you suggested and it seems to work well.Thank you.Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Ryan Metcalfe ***@***.***> Datum: 26/03/2024  01:07  (GMT+01:00) Aan: intel/openvino-plugins-ai-audacity ***@***.***> Cc: asterixlb ***@***.***>, Mention ***@***.***> Onderwerp: Re: [intel/openvino-plugins-ai-audacity] How can the results for songs be so different ? (Issue #48) 
Hi @asterixlb,
Sorry for the delay in trying this out. I tried 'El Bandido' on my side, and I was able to produce something reasonable (just a screenshot of the waveform):
image.png (view on web)
vs. yours, which seems to be mostly noise:
image.png (view on web)
I'm suspecting that perhaps you are experiencing this issue: #1 (which I think this is what @Elshara was hinting at)
One way to find out is, try to delete your %appdata%\audacity\openvino-model-cache folder (you can copy and paste that path into Windows explorer), and try running music sep on that El Bandido track again. If it's the same issue, the first time you run music separation after deleting that folder, you will get good output. The next time you run (no matter what track you use), it will produce bad results.
Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment] 2024-04-23 01:11
Hi @asterixlb,

Thanks for trying this out. Looks like you are indeed observing the caching issue, so I'll close as a duplicate of this issue: #1 

By the way, we have released an updated set of plugins here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

I'd be interested to hear whether the issue is fixed in this latest release. Thanks!

**Closed by RyanMetcalfeInt8** 2024-04-23 01:11 UTC

**Comment by asterixlb** [comment] 2024-04-25 11:33
I thought I already let you know that the problem is resolved.  Thanks. Verzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Ryan Metcalfe ***@***.***> Datum: 23/04/2024  03:11  (GMT+01:00) Aan: intel/openvino-plugins-ai-audacity ***@***.***> Cc: asterixlb ***@***.***>, Mention ***@***.***> Onderwerp: Re: [intel/openvino-plugins-ai-audacity] How can the results for songs be so different ? (Issue #48) 
Hi @asterixlb,
Thanks for trying this out. Looks like you are indeed observing the caching issue, so I'll close as a duplicate of this issue: #1
By the way, we have released an updated set of plugins here: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2
I'd be interested to hear whether the issue is fixed in this latest release. Thanks!
