### ISSUE TITLE
rotina de inicialização da biblioteca de vínculo dinâmico 

### ISSUE THREAD

**Issue by ADNILSONSANBRI** [intel/openvino-plugins-ai-audacity#37] opened 2024-01-30 12:55 UTC
Uma rotina de inicialização da biblioteca de vínculo dinâmico (dll) falhou

**Comment by RyanMetcalfeInt8** [comment] 2024-01-30 21:18
Hi @ADNILSONSANBRI,

I think this is a duplicate of this issue (https://github.com/intel/openvino-plugins-ai-audacity/issues/8), which I am still trying to determine the reason. 

I'll probably close this issue as duplicate, but can you please share some system info such as CPU version & Windows version? Thanks!

**Comment by RyanMetcalfeInt8** [comment] 2024-02-16 13:09
closing as duplicate

**Closed by RyanMetcalfeInt8** 2024-02-16 13:09 UTC
