### ISSUE TITLE
"Error sending data (12030)" while installing

### ISSUE THREAD

**Issue by SpringySpring04** [intel/openvino-plugins-ai-audacity#164] opened 2024-05-04 23:10 UTC
First time using the installer for current latest version of OpenVINO plugins for Audacity (v3.5.1-R2.1)
I'm receiving this error message:

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/47752258/2db6698c-9168-4635-809e-6f9269380dda)

From what I've seen, I think it may be a problem with AV or firewall, but I'm not really sure. Apparently many other people are having this issue as well. What do I do about this?

**Comment by SpringySpring04** [comment] 2024-05-04 23:20
UPDATE:
Running the installer as administrator starts the download properly.

**Comment by The3IC** [comment] 2024-05-05 05:30
Actually I saw the same error, my bacon was saved because I had the models already on my machine.

**Comment by RyanMetcalfeInt8** [comment] 2024-05-05 11:55
Hi @SpringySpring04,

Yes, this is a known issue and I'm not sure what exactly is causing it -- I cannot seem to reproduce it on my end. It's good to know that running as administrator seemed to help out in your case, I'll suggest others to try that as well.

Thanks,
Ryan

**Comment by RyanMetcalfeInt8** [comment] 2024-05-05 14:54
Hello, let's keep tracking this one on the original reported issue thread here: https://github.com/intel/openvino-plugins-ai-audacity/issues/129

Closing this one as duplicate

**Closed** 2024-05-05 14:54 UTC
