### ISSUE TITLE
Not recognizing Openvino module

### ISSUE THREAD

**Issue by surrealistsavaant** [intel/openvino-plugins-ai-audacity#56] opened 2024-02-15 18:47 UTC
Hello and thank you for your help! I'm trying to install the Openvino module on Windows by following the instructions on the download page. Referencing the video there should be a FirstTime.ini file in the Audacity folder that I do not have. Also, after transferring the cache.json file into the EffectsMenuDefault.xml of the Audacity folder I don't see the fbgemm.dll or fbjni.dll files like shown in the video. Tried transferring the openvino-models folder into the Audacity folder generally, since I don't have the FirstTime.ini to target, but Audacity is not seeing this module. My Audacity is 3.4.2, but doesn't reference R1. No updates are available. Please help!

**Comment by RyanMetcalfeInt8** [comment] 2024-02-15 19:47
Hi @surrealistsavaant,


> Referencing the video there should be a FirstTime.ini file in the Audacity folder that I do not have. Also, after transferring the cache.json file into the EffectsMenuDefault.xml of the Audacity folder I don't see the fbgemm.dll or fbjni.dll files like shown in the video.

Hmm, I would try completely uninstalling Audacity, deleting the left-over ```C:\Program Files\Audacity``` folder, and re-downloading everything again. It *should* be as easy as shown in the video, which is to just open the zip files and drag everything into the ```Audacity``` folder. 

> Tried transferring the openvino-models folder into the Audacity folder generally, since I don't have the FirstTime.ini to target

Hmm, I'm not really sure what you mean by this. You should be dragging files into the ```Audacity``` folder (the one containing Audacity.exe). Maybe in the video I accidently hovered over ```FirstTime.ini``` or something, and makes it seem like I'm doing something special with that file? If it does, sorry about the confusion -- I'm really just 1. Opening the zip files 2. Dragging the contents of the zip files into the Audacity folder.

**Comment by surrealistsavaant** [comment] 2024-02-15 21:36
Thank you! Yes, I did wonder if the FirstTime.ini was significant to this
issue because that was where you released the file. I didn’t think it
should matter, but the name suggested a relationship to the problem I was
having.

I will try the clean reinstall and post my results. Thanks again for the
help!

**Comment by RyanMetcalfeInt8** [comment] 2024-02-15 22:07
Awesome, glad you were able to get it running. Cheers!

**Comment by surrealistsavaant** [comment] 2024-02-15 22:12
Think I spoke too soon. :(  I was able to find and enable the module, but
upon restart I am getting this error:
[image: image.png]
Any thoughts?

**Comment by RyanMetcalfeInt8** [comment] 2024-02-15 22:25
hmm, can you try uploading that image again (and perhaps not via email reply)? It's not showing up.

**Comment by surrealistsavaant** [comment] 2024-02-15 22:30
Sorry about that, Here it is again.
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/160169002/38fde1b6-36ba-4d3d-b036-56074bb3075a)
Also, Audacity\modules\mod-openvino.dll is present.

**Comment by surrealistsavaant** [comment] 2024-02-15 22:34
Also, still no FirstTime.ini in Audacity folder. Don't know if that makes sense?

**Comment by surrealistsavaant** [comment] 2024-02-15 22:34
I really appreciate the help!

**Comment by RyanMetcalfeInt8** [comment] 2024-02-15 22:38
Thanks. Which version of Windows are you running, and what kind of CPU do you have? I've seen this issue pop up a few times (initialization error), and still trying to wrap my head around why it's happening to some users.

I have another issue where I'm tracking these kind of initialization issues, and I had posted some 'test' DLL's to help narrow down the root cause. See this issue / comment: https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1890998932

It might be worth running through those experiments. I think I concluded that most issues stem from the whisper transcription features for whatever reason.

**Comment by surrealistsavaant** [comment] 2024-02-15 22:44
Intel(R) Celeron(R) N4120 CPU @ 1.10GHz   1.10 GHz with Windows 11 Home.  

I'll have to try those experiments, thanks for the work.

**Comment by surrealistsavaant** [comment] 2024-02-15 22:46
Just realized how that last line might be taken wrong. Thanks for the work that you have done to troubleshoot this. :)

**Comment by RyanMetcalfeInt8** [comment] 2024-02-15 22:49
No problem, I may close this one as duplicate. But leaving it open for the time being so that I'll remember to respond in case I figure something out :)

**Comment by RyanMetcalfeInt8** [comment] 2024-02-15 22:51
BTW, your CPU should be supported -- the only potential issue that I see would be for, again, whisper transcription as I compiled whisper.dll to use AVX/AVX2 instructions -- but your CPU only supports up to SSE4.2. Anyway, I don't *think* it would cause an initialization issue though...

**Closed** 2024-03-08 13:12 UTC
