### ISSUE TITLE
Windows install fails (Error 12030)

### ISSUE THREAD

**Issue by ezradlesser** [intel/openvino-plugins-ai-audacity#153] opened 2024-04-28 17:39 UTC
I am not able to install the plugins on Windows 11 using the latest 3.5.1 executable.
After selecting "recommended" modules, I receive an error:
```Error sending data: (12030) The connection with the server was terminated abnormally.```
[Screenshot](https://i.imgur.com/GtggVh7.png).
Running the installer as admin does not seem to fix the issue.

A quick Google search reveals:
"Microsoft defines the WinHttpSendRequest Error[12030] as: 12030: ERROR_WINHTTP_CONNECTION_ERROR The connection with the server has been reset or terminated, or an incompatible SSL protocol was encountered."
https://community.carbonblack.com/t5/Knowledge-Base/App-Control-Agent-Upgrade-WinHttpSendRequest-Error-12030/ta-p/72663

**Comment by RyanMetcalfeInt8** [comment] 2024-05-05 14:55
Hello, I am still trying to understand what is causing this issue for some folks.

The original reported issue thread is here: https://github.com/intel/openvino-plugins-ai-audacity/issues/129

Closing this one as duplicate

**Closed by RyanMetcalfeInt8** 2024-05-05 14:55 UTC

**Comment by GemaRojaCl** [comment] 2024-05-20 03:10
I have Windows 10 and I am experiencing the same problem; giving the installer administrator permissions does NOT solve it.

**Comment by RyanMetcalfeInt8** [comment] 2024-05-20 14:18
Hi @ezradlesser, @GemaRojaCl, has your Windows installation kept up to date with updates, etc?

Couple of experiments:
1. Can you access this page (from a web browser)? https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main
2. If so, if you were to open a powershell terminal from your Downloads folder and run the following, does it succeed?
```
Invoke-WebRequest https://huggingface.co/Intel/whisper.cpp-openvino-models/resolve/194efafbee09390bbf33f33d02d9856dacfdd162/ggml-base-models.zip -OutFile ggml-base-models.zip
```

**Comment by GemaRojaCl** [comment] 2024-05-22 02:19
Hi Ryan Metcalfe <https://github.com/RyanMetcalfeInt8>

Thanks for responding..


   1. has you Windows installation kept up to date with updates, etc?

Windows 10 Home 22H2, Last update, May 15, 2024

   2. Can you access this page (from a web browser)?
   https://huggingface.co/Intel/whisper.cpp-openvino-models/tree/main

yes..!!!

   3. If so, if you were to open a powershell terminal from your Downloads
   folder and run the following, does it succeed?

error message:

Invoke-WebRequest : Se ha terminado la conexión: Error inesperado de envío.
En línea: 1 Carácter: 1

   - Invoke-WebRequest https://huggingface.co/Intel/whisper.cpp-openvino-m
   ...
   -

     + CategoryInfo          : InvalidOperation:
(System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
    eption
     + FullyQualifiedErrorId :
WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand


Today, I checked the Windows Firewall to see if it was blocking anything. I
enabled the log for blocks and ran the script in PowerShell, but there is
nothing in the log. So, it appears that the firewall is not the cause.

Regards!!
