### ISSUE TITLE
Audacity Crash after installing Vino

### ISSUE THREAD

**Issue by Maraco79** [intel/openvino-plugins-ai-audacity#224] opened 2024-06-03 12:21 UTC
Hi, I downloaded Audacity (audacity-win-3.5.1-64bit.exe) the muse fx, and the openvino FXs, Installed Audacity and it opened fine, but when I installed the Vino plugins it crashes on startup and will not open anymore, I have tried reinstalling with no luck.

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/171575007/e2e2b4b4-2493-482d-a129-0f197b3aa470)

and the error log:

[Audacity Crash.txt](https://github.com/user-attachments/files/15533666/Audacity.Crash.txt)

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/171575007/5d3395b8-58bb-4304-867e-b6e69f15b97a)

**Comment by RyanMetcalfeInt8** [comment] 2024-06-03 12:31
Hmm, strange. The crash report seems to show a backtrace to the GPU plugin. Can you try something? You should find a file, ```C:\Program Files\Audacity\OpenCL.dll```. Can you try removing this file from this folder (just move it someplace else, like your Downloads folder or something), and re-running Audacity. Is the issue resolved, the same, or is there some new issue?

**Comment by Maraco79** [comment] 2024-06-03 13:11
> Hmm, strange. The crash report seems to show a backtrace to the GPU plugin. Can you try something? You should find a file, `C:\Program Files\Audacity\OpenCL.dll`. Can you try removing this file from this folder (just move it someplace else, like your Downloads folder or something), and re-running Audacity. Is the issue resolved, the same, or is there some new issue?

Thank you!!!!! that resolved the issue and now I'm able to open Audacity with no problems and the Vino plugins also work!

**Comment by RyanMetcalfeInt8** [comment] 2024-06-03 13:23
Glad it's working! Hmm, but now I need to figure out why the packaged OpenCL.dll is causing Audacity to crash in some cases. Anyway, thanks for trying it out and getting back to me!

**Comment by atribolini** [comment] 2024-06-11 06:02
I have the same crash on open - I moved the .DLL as you suggested but that fix didn't work for me - still crashing.

![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/62003906/d516436c-65c1-4898-866b-635f9e0d7874)
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/62003906/1062d204-c5f6-4909-8d06-071e21260dd2)

[audacity crash report.txt](https://github.com/user-attachments/files/15782914/audacity.crash.report.txt)

**Comment by RyanMetcalfeInt8** [comment] 2024-06-15 15:32
Hi @atribolini,

Sorry for delay. Hmm, I'm not really sure why it would be crashing in your case. Are your GPU drivers up to date?

**Comment by atribolini** [comment] 2024-06-16 20:36
Hi Ryan - I updated the intel HD graphics driver from the Dell website. I also re-installed audacity with the muse installer. (I had previously used the audacity installer)

Then I re-installed openvino. Now it's working (even with the openCL.dll still in the audacity folder).

Not sure which of these fixed the problem but thanks for the driver suggestion.

**Comment by RyanMetcalfeInt8** [comment] 2024-06-17 12:27
Hi @atribolini,

I'm glad the problem is resolved. I *think* the issue was most likely fixed with the GPU driver update -- if there was any incompatibility with OpenCL that was causing the problem, then this would have been the thing that fixed it.

**Closed by RyanMetcalfeInt8** 2024-06-17 12:27 UTC
Labels: bug
