### ISSUE TITLE
Unable to load "mod-openvino" module (Windows 11 ARM64)

### ISSUE THREAD

**Issue by petapika** [intel/openvino-plugins-ai-audacity#18] opened 2024-01-05 23:30 UTC
After installation, I enabled mod-openvino in Preferences|Modules and then closed/re-started Audacity, I get a "Module Unsuitable" dialog that says, "Unable to load the "mod-openvion" module. Error: A DLL initialization routine failed."

This is from Audacity v 3.4.2 running in x86 mode on Windows 11 Arm64, virtualized under UTM Version 4.4.4 (92) on MacOS Sonoma (14.2.1) on MacBook Pro 2021 M1 max 32GB RAM.

Edit/update: I reverified this after restarting Win11 and trying again. Same error.

**Comment by Zzooheir19975** [comment] 2024-01-06 10:10
Mêmes. Problème  une routine d'initialisation de DLL a échoué. "

**Comment by Zzooheir19975** [comment] 2024-01-06 10:11
Mêmes. Problème une routine d'initialisation de DLL a échoué. " windows11 64 bits

**Comment by RyanMetcalfeInt8** [comment] 2024-01-06 14:00
Hi @petapika , @Zzooheir19975,

I haven't yet tried this in an ARM64 virtualized environment. You're using 3.4.2 x86 version of Audacity? 

Thanks,
Ryan

**Comment by petapika** [comment] 2024-01-06 16:34
> Hi @petapika , @Zzooheir19975,
> 
> I haven't yet tried this in an ARM64 virtualized environment. You're using 3.4.2 x86 / 64-bit version of Audacity?

Correct -- Audacity 3.4.2 for Windows. It shows in Win11-arm64 task manager as x64. Tried this again after rebooting Win11. Same error.

**Comment by grt26** [comment] 2024-01-08 08:22
I got same problem as Petapika. Running under Win10 with an AMD processor. Any idea? Thanks in advance.

**Comment by RyanMetcalfeInt8** [comment] 2024-01-08 14:09
Hi @grt26, @petapika,

As I said in issue #8 , I'm having trouble understanding / reproducing these DLL initialization issues -- I'll come up with, and share some small test executable that will hopefully shed some light on what's going on.

Thanks,
Ryan

**Comment by grt26** [comment] 2024-01-08 18:01
Hi Ryan, thanks for your fst response. I tried again Installation as per video, and found that there was another zip files which I simply extracted to the selected folder, .../audacity and started audacity, set mod-openvino to active, exit audacity and restarted it. Then i found the relevant tool folder. Perfect work for separate voice and music.Thanks again, my issue can be closed.Best regards and have a nice day, Günther Am 08.01.2024 15:09 schrieb Ryan Metcalfe ***@***.***>:
Hi @grt26, @petapika,
As I said in issue #8 , I'm having trouble understanding / reproducing these DLL initialization issues -- I'll come up with, and share some small test executable that will hopefully shed some light on what's going on.
Thanks,
Ryan

**Comment by petapika** [comment] 2024-01-09 20:02
> Hi Ryan, thanks for your fst response. I tried again Installation as per video, and found that there was another zip files which I simply extracted to the selected folder, .../audacity and started audacity, set mod-openvino to active, exit audacity and restarted it. Then i found the relevant tool folder. Perfect work for separate voice and music.Thanks again, my issue can be closed.Best regards and have a nice day, Günther Am 08.01.2024 15:09 schrieb Ryan Metcalfe ***@***.***>: Hi @grt26, @petapika, As I said in issue #8 , I'm having trouble understanding / reproducing these DLL initialization issues -- I'll come up with, and share some small test executable that will hopefully shed some light on what's going on. Thanks, Ryan —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Can you describe what you mean when you say there was another zip file you found and extracted?

I reviewed the installation video and realized that it says to copy the 3.4.2-R1 zip file contents to the Audacity folder. I had previously only installed the current 3.4.2 download/release using the exe installer. So I tried copying the R1 release from the zip file to the Audacity folder, the recopied the openvino-models zip file contents to the Audacity folder and still got the same error. 

I completely removed Audacity, reinstalled, and then used the install video for openvino and tried again, and got the exact same error. The only thing that was different in my installation from the video is that when I dropped the openvion-models folder into Audacity it said you need admin perms with a Continue button which I pressed and the copy completed.

**Comment by grt26** [comment] 2024-01-10 07:46
Dear all:

concerning your question about another zip file:

I completely removed Audacity, both by deinstallation, and after this step, by removing all files in the remaining directory c:\programme\audacity. This folder was empty.

Then I first installed Audacity 3.4.2 again. 
Following your video, I copied the both zip-Files into the c:\programme\audacity folder by confirming all and also allowing administration rights.
I started audacity, set the open-vino from new to active, and terminated audacity. Starting again, I got the message: „unable to load mod-openvino module“.
I terminated Audacity, used the windows explorer and found mod-openvino.zip file in the folder.
I exctracted this file by clicking on the name, and the mod-openvino dlls were extracted into the audacity folder.
Then, after starting audacity again, I found now in the Effect menue of audactiy the OpenVINO AI Effects.

 

Hope this helps in understanding my problem solution.

BR Günther 

 

Von: petapika ***@***.***> 
Gesendet: Dienstag, 9. Januar 2024 21:03
An: intel/openvino-plugins-ai-audacity ***@***.***>
Cc: grt26 ***@***.***>; Mention ***@***.***>
Betreff: Re: [intel/openvino-plugins-ai-audacity] Unable to load "mod-openvino" module (Windows 11 ARM64) (Issue #18)

 

Hi Ryan, thanks for your fst response. I tried again Installation as per video, and found that there was another zip files which I simply extracted to the selected folder, .../audacity and started audacity, set mod-openvino to active, exit audacity and restarted it. Then i found the relevant tool folder. Perfect work for separate voice and music.Thanks again, my issue can be closed.Best regards and have a nice day, Günther Am 08.01.2024 15:09 schrieb Ryan Metcalfe @.>: Hi @grt26 <https://github.com/grt26> , @petapika <https://github.com/petapika> , As I said in issue #8 <https://github.com/intel/openvino-plugins-ai-audacity/issues/8>  , I'm having trouble understanding / reproducing these DLL initialization issues -- I'll come up with, and share some small test executable that will hopefully shed some light on what's going on. Thanks, Ryan —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: @.>

Can you describe what you mean when you say there was another zip file you found and extracted?

I reviewed the installation video and realized that it says to copy the 3.4.2-R1 zip file contents to the Audacity folder. I had previously only installed the current 3.4.2 download/release using the exe installer. So I tried copying the R1 release from the zip file to the Audacity folder, the recopied the openvino-models zip file contents to the Audacity folder and still got the same error.

I completely removed Audacity, reinstalled, and then used the install video for openvino and tried again, and got the exact same error. The only thing that was different in my installation from the video is that when I dropped the openvion-models folder into Audacity it said you need admin perms with a Continue button which I pressed and the copy completed.

**Comment by petapika** [comment] 2024-01-10 19:56
OK, I have a new indication... In Audacity prefs, instead of Enabled, I set openvino to "Ask" and restarted Audacity. 

I got a dialog from Audacity Module Loader saying: Module "mod-openvino" found.   Try and load this module? Selected Yes and got same error. 

So we know it's finding the module, it's just not able to init the DLL?

**Comment by RyanMetcalfeInt8** [comment] 2024-01-10 20:02
Hi @petapika,

> So we know it's finding the module, it's just not able to init the DLL?
Right -- It seems that Audacity is able to see that mod-openvino.dll is present. It then tries to load it, and this is where the trouble is.

Could you download the little OpenVINO tester .exe, and follow instructions that I put here? 
https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1885082523

It would be useful to understand if this 'hello_query_device.exe' application is able to run in your env.

Thanks,
Ryan

**Comment by petapika** [comment] 2024-01-11 18:40
> Could you download the little OpenVINO tester .exe, and follow instructions that I put here? [#8 (comment)](https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1885082523)
> 
> It would be useful to understand if this 'hello_query_device.exe' application is able to run in your env.

Sorry, thought I sent this yesterday... Here's what I got from that exe. Is this what you would expect?

==============================
PS C:\Program Files (x86)\Audacity> .\hello_query_device.exe
[ INFO ] Build ................................. 2023.1.0-12185-9e6b00e51cd-releases/2023/1
[ INFO ]
[ INFO ] Available devices:
[ INFO ] CPU
[ INFO ]        SUPPORTED_PROPERTIES:
[ INFO ]                Immutable: AVAILABLE_DEVICES : ""
[ INFO ]                Immutable: RANGE_FOR_ASYNC_INFER_REQUESTS : 1 1 1
[ INFO ]                Immutable: RANGE_FOR_STREAMS : 1 8
[ INFO ]                Immutable: FULL_DEVICE_NAME :                           Virtual CPU @ 1.00GHz
[ INFO ]                Immutable: OPTIMIZATION_CAPABILITIES : FP32 FP16 INT8 BIN EXPORT_IMPORT
[ INFO ]                Mutable: NUM_STREAMS : 1
[ INFO ]                Mutable: AFFINITY : NONE
[ INFO ]                Mutable: INFERENCE_NUM_THREADS : 0
[ INFO ]                Mutable: PERF_COUNT : NO
[ INFO ]                Mutable: INFERENCE_PRECISION_HINT : f32
[ INFO ]                Mutable: PERFORMANCE_HINT : LATENCY
[ INFO ]                Mutable: EXECUTION_MODE_HINT : PERFORMANCE
[ INFO ]                Mutable: PERFORMANCE_HINT_NUM_REQUESTS : 0
[ INFO ]                Mutable: ENABLE_CPU_PINNING : YES
[ INFO ]                Mutable: SCHEDULING_CORE_TYPE : ANY_CORE
[ INFO ]                Mutable: ENABLE_HYPER_THREADING : YES
[ INFO ]                Mutable: DEVICE_ID : ""
[ INFO ]                Mutable: CPU_DENORMALS_OPTIMIZATION : NO
[ INFO ]                Mutable: CPU_SPARSE_WEIGHTS_DECOMPRESSION_RATE : 1
[ INFO ]
[ INFO ] GNA
[ INFO ]        SUPPORTED_PROPERTIES:
[ INFO ]                Immutable: AVAILABLE_DEVICES : GNA_SW
[ INFO ]                Immutable: OPTIMAL_NUMBER_OF_INFER_REQUESTS : 1
[ INFO ]                Immutable: RANGE_FOR_ASYNC_INFER_REQUESTS : 1 1 1
[ INFO ]                Immutable: OPTIMIZATION_CAPABILITIES : INT16 INT8 EXPORT_IMPORT
[ INFO ]                Immutable: FULL_DEVICE_NAME : GNA_SW
[ INFO ]                Immutable: GNA_LIBRARY_FULL_VERSION : 3.5.0.2116
[ INFO ]                Mutable: GNA_DEVICE_MODE : GNA_SW_EXACT
[ INFO ]                Mutable: PERFORMANCE_HINT : LATENCY
[ INFO ]                Mutable: LOG_LEVEL : LOG_NONE
[ INFO ]                Immutable: EXECUTION_DEVICES : GNA
[ INFO ]                Mutable: GNA_SCALE_FACTOR_PER_INPUT : ""
[ INFO ]                Mutable: GNA_FIRMWARE_MODEL_IMAGE : ""
[ INFO ]                Mutable: GNA_HW_EXECUTION_TARGET : UNDEFINED
[ INFO ]                Mutable: GNA_HW_COMPILE_TARGET : UNDEFINED
[ INFO ]                Mutable: GNA_PWL_DESIGN_ALGORITHM : UNDEFINED
[ INFO ]                Mutable: GNA_PWL_MAX_ERROR_PERCENT : 1.000000
[ INFO ]                Mutable: INFERENCE_PRECISION_HINT : undefined
[ INFO ]                Mutable: EXECUTION_MODE_HINT : ACCURACY
[ INFO ]                Mutable: PERFORMANCE_HINT_NUM_REQUESTS : 1
[ INFO ]
PS C:\Program Files (x86)\Audacity>
==============================

**Comment by RyanMetcalfeInt8** [comment] 2024-01-11 18:43
Hi @petapika,

Thanks. Okay, so given that this standalone OpenVINO tester works, it kind of proves that OpenVINO by itself isn't the issue (e.g. it doesn't require any extra DLLs, etc.). 

I guess I'll have to produce a couple more small test apps that layer the other dependencies (like libtorch, whisper) one-by-one -- to narrow down exactly where the issue is coming from for the 'full' Audacity plugin.

**Comment by petapika** [comment] 2024-01-11 18:46
Thanks, and let me know if I can help with any other testing. 

I will go see if I can make this work on another VM I have on an intel Mac, but it's Windows 10.

**Comment by RyanMetcalfeInt8** [comment] 2024-01-14 16:39
Hi @petapika,

I think I already pinged you on other issue thread, but just to re-emphasize -- it would be good to get results of the experiment described here: https://github.com/intel/openvino-plugins-ai-audacity/issues/8#issuecomment-1890998932

This will help me narrow down which of the dependencies are causing DLL loading issues.

Thanks again!
Ryan

**Comment by connect2y** [comment] 2024-03-07 09:54
I have the same issue. I tried on an Intel based Windows 10 and downloaded the 2 separate files. Audacity was just about 100 MB while the 2 files uncompressed to more than 5 GB.  In pursuit of a better sound I followed the instructions given. But the message was openvino-models.dll file refused to open from the library. It gets enabled, but shows as failed on restart of Audacity . So much so. Maybe you can find a solution. I am eager to try it out again.

**Comment by RyanMetcalfeInt8** [comment] 2024-03-08 13:25
Hi @connect2y, what is the CPU model that you are using? 

By the way, you said it's an Intel-based machine, and you are commenting on a issue that is tracking issues with ARM64.

**Comment by connect2y** [comment] 2024-03-08 16:01
Hi Ryan,  Much before I read about the issues, i downloaded the 2 files cause the heading of your software starts with the word Intel.  The cpu in my dell notebook is an Intel i5 quad processor with windows 10. The Realtech drivers are pretty cool for social media apps online but I wanted something else.  To record voice with my guitar. Hence Audacity and then your software. .. rest is as i had written before.  My intention is to help you with the details.  Since, you and the group has worked till now on this project, i hope it works out soon.

**Comment by RyanMetcalfeInt8** [comment] 2024-03-08 16:36
Hi @connect2y, could you give the specific CPU model that you're using? For example, in Windows settings, go to System->About, and it should list the full model details. For example, the PC that I am on right now is:
```
11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz   3.00 GHz
```
Thanks,
Ryan

**Comment by connect2y** [comment] 2024-03-08 17:49
Ryan, this  is from the Windows 10 system.. Processor : Intel(R) Core (TM) i5 CPU   M430 @ 2.27 GHz  2.27 GHz.
Hope this helps

**Comment by RyanMetcalfeInt8** [comment] 2024-03-08 17:55
Hi @connect2y,

Yes, that helps, thank you. I think the issue is that the CPU that you are using doesn't support AVX/AVX2 extensions. 

Go here, and look at *Instruction Set Instructions*, and you'll see it only supports up to SSE4.2:
https://www.intel.com/content/www/us/en/products/sku/43537/intel-core-i5430m-processor-3m-cache-2-26-ghz/specifications.html

The issue is that one of dependencies, whisper, uses AVX/AVX2 instructions by default and so there are issues loading the module in this case that causes the 'unable to load mod-openvino' error.

Thanks,
Ryan

**Comment by connect2y** [comment] 2024-03-10 08:55
Ryan, 
I didnt realize my processor was missing avx/avx2 till you brought it up. I checked with Intel documents online and did diagnostics on the cruel dude. There is more than 80 percent chance that you have got it right. Intel, as usual wants to maintain silence, cause its embarrassing to them.

Cya, till next time

Bala Venkit

**Comment by jonCates** [comment] 2024-03-14 10:14
hi all, im on a new Windows 11 Pro (Version 22H2) MSI laptop, with 13th Gen Intel(R) Core(TM) i7-1360P 2.20 GHz, having same problems described above by others.  followed instructions (multiple times) but consistently getting the "Module Unsuitable" dialog with the "Unable to load the "mod-openvino" module Error: The specified module could not be found." (also reinstalled Audacity, etc, same problem.) any suggestions? im rly hoping to work w/ OpenVINO in Audacity...

**Comment by RyanMetcalfeInt8** [comment] 2024-03-14 12:32
Hi @jonCates,

Sorry to hear that you're having trouble getting it to work.. your PC should definitely be able to run these plugins.

Since it sounds like it's a new laptop, my first thought is that perhaps it's missing the Visual Studio redistributable packages. Can you go here (https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170), and download / install [vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe)?

After doing that, you may need to open up Audacity and re-set the module to 'Enabled' in preferences again, close and re-open it. Let me know if this solves the issue... otherwise we can figure out next steps to determine what the problem is.

Thanks!
Ryan

**Comment by jonCates** [comment] 2024-03-16 07:51
> RyanMetcalfeInt8
thankYou, sorry to say that i just downloaded / installed vc_redist.x64.exe but i encounter the same error...

**Comment by jonCates** [comment] 2024-03-16 07:52
thankYou, sorry to say that i just downloaded / installed vc_redist.x64.exe but i encounter the same error...

**Comment by RyanMetcalfeInt8** [comment] 2024-03-17 21:52
Hi @jonCates,

Shoot. I've just posted to our wiki the method that you can use to debug a DLL dependency issue:
https://github.com/intel/openvino-plugins-ai-audacity/wiki/Debugging-DLL-dependency-issues-on-Windows

Can you try to follow these steps and see if you can determine which DLL is missing?

Thanks!
Ryan

**Comment by jonCates** [comment] 2024-04-11 09:29
thank you so much for all of your help, i think its resolved now and i think the problems were being caused by FFMPEG, so ive removed FFMPEG from my system

**Comment by RyanMetcalfeInt8** [comment] 2024-04-23 01:24
Hi all,

We have posted an updated release: https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.0-R2

Please give it a shot and hopefully some of these 'unable to load module' issues are resolved with this version.

I'm going to close this issue for now, but feel free to keep commenting on this one if you have questions / want to share results, or open another ticket if you still have issues.

Thanks!
Ryan

**Closed by RyanMetcalfeInt8** 2024-04-23 01:24 UTC
