### ISSUE TITLE
Transcript fails 3.5.1-R2

### ISSUE THREAD

**Issue by The3IC** [intel/openvino-plugins-ai-audacity#143] opened 2024-04-26 08:23 UTC
Opening a new error for this as this error seems to be independent of the character set problem.

Testing out transcript generation but it fails with error:

11:11:33: Operation 'Pre-processing' took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
11:11:39: Error: In Whisper Transcription Effect, exception: invalid map<K, T> key
11:11:41: Operation 'OpenVINO Whisper Transcription' took 6.211000 seconds. Poll was called 1696 times and took 0.045100 seconds. Yield was called 36 times and took 0.021169 seconds.

Other OpenVivo functions work:
- music generation 
- noise reduction

New test setup (same error occurs on both my desktop - as reported earlier - as well as my laptop (this report):
Windows 10 (latest version)
Audacity 3.5.1
OpenVivo 3.5.1-R2
Normal installations
Account with no "strange" characters

Generation setup:
model: base and large-V3
CPU and GPU as per attached screenshot
error seems to occur when loading model (see attached screeenshot)?

![setupvivo](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/a46c9fa6-9e02-4399-acc8-7569601656a9)

![vivoerror](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/028effb3-13b7-418f-b817-3b4bd71dbf8a)

**Comment by RyanMetcalfeInt8** [comment] 2024-04-27 11:31
Hi @The3IC,

Thanks for reporting this as a separate issue. I'm a little bit surprised, actually, that you found it being unrelated to having special characters in the username. On one of my test systems, I get this error for a username that I created specifically with some special characters, and on other usernames using the same installation, it works.

Thanks,
Ryan

**Comment by bluemoehre** [comment] 2024-04-28 20:32
I checked with both username variants on my machine and the logged error occurs all time. I also assume it is not related to the ASCII/Unicode thing.

**Comment by RyanMetcalfeInt8** [comment] 2024-04-30 14:30
@bluemoehre, got it -- thanks for confirming that. 

Sorry for the delay -- Let me find some time to dig into the root cause on the one machine / account that I can reproduce this.

Thanks!

**Comment by fermarper** [comment] 2024-05-01 22:23
Hello. Exactly the same problem on my computer.
23:20:51: Audacity 3.5.1
Log Cleared.
23:21:09: Operation 'Pre-processing' took 0,000000 seconds. Poll was called 0 times and took 0,000000 seconds. Yield was called 0 times and took 0,000000 seconds.
23:21:10: Error: In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed
23:21:12: Operation 'OpenVINO Whisper Transcription' took 1,515000 seconds. Poll was called 396 times and took 0,033539 seconds. Yield was called 11 times and took 0,025412 seconds.
23:21:10: Error: whisper_ctx_init_openvino_encoder failed for device = GPU

**Comment by fermarper** [comment] 2024-05-01 22:24
Hello. Exactly the same problem on my computer.

23:20:51: Audacity 3.5.1
Log Cleared.
23:21:09: Operation 'Pre-processing' took 0,000000 seconds. Poll was called 0 times and took 0,000000 seconds. Yield was called 0 times and took 0,000000 seconds.
23:21:10: Error: In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed
23:21:12: Operation 'OpenVINO Whisper Transcription' took 1,515000 seconds. Poll was called 396 times and took 0,033539 seconds. Yield was called 11 times and took 0,025412 seconds.
23:21:10: Error: whisper_ctx_init_openvino_encoder failed for device = GPU

**Comment by RyanMetcalfeInt8** [comment] 2024-05-01 23:59
> Hello. Exactly the same problem on my computer.
> 
> 23:20:51: Audacity 3.5.1 Log Cleared. 23:21:09: Operation 'Pre-processing' took 0,000000 seconds. Poll was called 0 times and took 0,000000 seconds. Yield was called 0 times and took 0,000000 seconds. 23:21:10: Error: In Whisper Transcription Effect, exception: whisper.cpp context creation / initialization failed 23:21:12: Operation 'OpenVINO Whisper Transcription' took 1,515000 seconds. Poll was called 396 times and took 0,033539 seconds. Yield was called 11 times and took 0,025412 seconds. 23:21:10: Error: whisper_ctx_init_openvino_encoder failed for device = GPU

Hi @fermarper, this one is also a ```whisper_ctx_init_openvino_encoder failed```, but I don't see ```invalid map<K, T> key```, so it seems a bit different to me. Does it work on CPU, and what kind of GPU do you have?

**Comment by fermarper** [comment] 2024-05-02 12:14
Good morning.
Indeed, when I select CPU it opens fine, but the subtitles appear with symbols. They are not real subtitles.
Regarding the GPU of my computer, I attach characteristics. Best regards. Thanks for your help.
![GPU](https://github.com/intel/openvino-plugins-ai-audacity/assets/168686362/707928bd-b64e-4faa-829b-e9cade25e572)

**Comment by RyanMetcalfeInt8** [comment] 2024-05-02 13:34
Hi @The3IC, @bluemoehre,

 On your system, would you mind capturing a log from the installer for me?

It can be done like this (from a cmd.exe window): 
```
audacity-win-v3.5.1-R2-64bit-OpenVINO-AI-Plugins.exe /LOG=installer_log.txt
```

You only need to run the very beginning of the installer, until the 'welcome' screen shows up (attached pic):
![image](https://github.com/intel/openvino-plugins-ai-audacity/assets/107415876/20803047-33c9-45aa-a6a9-8254219877e4)

You can just hit 'cancel' at that point.  I really am only interested in the message at the end about whether it detected your system to support AVX2 or not. For example, on mine it looks like this:
```
2024-05-02 09:20:03.127   This system supports AVX2
```
Since you successfully used the older set of plugins, I assume your system also supports AVX2 -- so I am making sure that this is indeed reflected in your log. 

Thanks,
Ryan

**Comment by fermarper** [comment] 2024-05-02 14:33
Ok
I will do it later when I get home.
Thanks a lot for you help

A quinta, 2/05/2024, 14:34, Ryan Metcalfe ***@***.***>
escreveu:

**Comment by The3IC** [comment] 2024-05-02 17:05
@RyanMetcalfeInt8 here is the log. A couple of observations, no idea if this is a problem:

- the name of the temp directory is a bit weird but it seems to have been created?
- see screenshot with access problem?

![access](https://github.com/intel/openvino-plugins-ai-audacity/assets/1484296/e02609c2-48ac-49b3-b1e5-3f045a7b23a7)

Installer error?
- the temporary directory is left even after the install is terminated, the installer should preferable clean out any temporary stuff that it creates.

--------------

og opened. (Time zone: UTC+03:00)
2024-05-02 19:44:34.527   Setup version: Inno Setup version 6.2.2
2024-05-02 19:44:34.527   Original Setup EXE: C:\Users\Håkan\Downloads\audacity-win-v3.5.1-R2-64bit-OpenVINO-AI-Plugins.exe
2024-05-02 19:44:34.527   Setup command line: /SL5="$205B4,74900827,832512,C:\Users\Håkan\Downloads\audacity-win-v3.5.1-R2-64bit-OpenVINO-AI-Plugins.exe" /SPAWNWND=$105B2 /NOTIFYWND=$704D8 /LOG=installer_log.txt
2024-05-02 19:44:34.527   Compatibility mode: Yes (Installer)
2024-05-02 19:44:34.527   Windows version: 10.0.19045  (NT platform: Yes)
2024-05-02 19:44:34.527   64-bit Windows: Yes
2024-05-02 19:44:34.527   Processor architecture: x64
2024-05-02 19:44:34.527   User privileges: Administrative
2024-05-02 19:44:34.527   Administrative install mode: Yes
2024-05-02 19:44:34.527   Install mode root key: HKEY_LOCAL_MACHINE
2024-05-02 19:44:34.527   64-bit install mode: Yes
2024-05-02 19:44:34.527   Created temporary directory: C:\Users\HKAN~1\AppData\Local\Temp\is-KNJJP.tmp
2024-05-02 19:44:34.527   -- DLL function import --
2024-05-02 19:44:34.527   Function name: IsProcessorFeaturePresent
2024-05-02 19:44:34.527   DLL name: kernel32.dll
2024-05-02 19:44:34.527   Dest DLL name: kernel32.dll
2024-05-02 19:44:34.527   Importing the DLL function.
2024-05-02 19:44:34.527   Successfully imported the DLL function. Delay loaded? No
2024-05-02 19:44:34.589   This system supports AVX2
2024-05-02 19:44:34.672   FindAudacity called
2024-05-02 19:45:12.317   Message box (Yes/No):

**Comment by RyanMetcalfeInt8** [comment] 2024-05-02 22:55
> the temporary directory is left even after the install is terminated, the installer should preferable clean out any temporary stuff that it creates.

Missed this one. Hmm, really? I'll double check this on my side -- it should be getting cleaned up automatically, as per this  [this documentation](https://jrsoftware.org/ishelp/index.php?topic=consts) 
```
...
Temporary directory used by Setup or Uninstall. This is not the value of the user's TEMP environment variable. It is a subdirectory of the user's temporary directory which is created by Setup or Uninstall at startup (with a name like "C:\WINDOWS\TEMP\IS-xxxxx.tmp"). All files and subdirectories in this directory are deleted when Setup or Uninstall exits. During Setup, this is primarily useful for extracting files that are to be executed in the [Run] section but aren't needed after the installation.
...
```

**Comment by The3IC** [comment] 2024-05-03 06:06
I guess it might be removed if you get to the end, but now when I cancelled in the middle, the directory was still there (as you can see from the screen grabs)

**Comment by fermarper** [comment] 2024-05-03 09:35
Hi Ryan
Yes,   my CPU supports AVX2.
Please , see the attached.
Thanks a lot


Fernando Marques ***@***.***> escreveu (quinta, 2/05/2024 à(s)
23:35):

**Comment by Al51n** [comment] 2024-05-03 13:49
I installed Audacity 5.1 and OpenVino 5.2R2.
When I go to transcribe I get the following error:
15:42:24: Audacity 3.5.1
15:42:24: Error: Failed to load shared library ‘avformat-60.dll’ (error 126: The specified module could not be found.)
15:42:24: Error: Failed to load shared library ‘avformat-59.dll’ (error 126: The specified module could not be found.)
15:42:24: Error: Failed to load shared library ‘avformat-58.dll’ (error 126: The specified module could not be found.)
15:42:24: Error: Failed to load shared library ‘avformat-57.dll’ (error 126: The specified module could not be found.)
15:42:24: Error: Failed to load shared library ‘avformat-55.dll’ (error 126: The specified module could not be found.)
15:42:31: Error: Failed to load shared library ‘avformat-60.dll’ (error 126: The specified module could not be found.)
15:42:31: Error: Failed to load shared library ‘avformat-59.dll’ (error 126: The specified module could not be found.)
15:42:31: Error: Failed to load shared library ‘avformat-58.dll’ (error 126: The specified module could not be found.)
15:42:31: Error: Failed to load shared library ‘avformat-57.dll’ (error 126: The specified module could not be found.)
15:42:31: Error: Failed to load shared library ‘avformat-55.dll’ (error 126: The specified module could not be found.)
15:42:38: Loaded 72 string 2.474609 Kb in size
15:42:38: Project loaded in 130 ms
15:43:08: Operation ‘Pre-processing’ took 0.000000 seconds. Poll was called 0 times and took 0.000000 seconds. Yield was called 0 times and took 0.000000 seconds.
15:43:12: Error: In Whisper Transcription Effect, exception: invalid map<K, T> key
15:43:20: Operation ‘OpenVINO Whisper Transcription’ took 3.875000 seconds. Poll was called 247 times and took 0.100867 seconds. Yield was called 40 times and took 0.039453 seconds

My PC is an up to date Win 10 with an i7-3770K processor & 16GB Ram. No graphics card. Running Win Pro.
I could see an issue having no graphics but I understood VinoAI was using the CPU.

**Comment by RyanMetcalfeInt8** [comment] 2024-05-03 14:20
Hi @Al51n,

Yes, you are experiencing the same issue. Fix is coming soon. I'll comment on this thread when it's ready.

Thanks!

**Comment by RyanMetcalfeInt8** [comment] 2024-05-03 19:20
Hi @The3IC, @bluemoehre, all, 

The patch release is now available. Can you give it a shot and let me know if it's resolved for you?

https://github.com/intel/openvino-plugins-ai-audacity/releases/tag/v3.5.1-R2.1

Thanks!

**Comment by RyanMetcalfeInt8** [comment] 2024-05-03 19:54
By the way @The3IC, this version should also resolve the issue where the tmp directory was not getting cleaned up.

**Comment by fermarper** [comment] 2024-05-03 22:06
Hi Ryan
I installed the patch but in my case the error persists. Maybe I'll have to
uninstall Audacity, install it again and reinstall the patch. What do you
think?

Ryan Metcalfe ***@***.***> escreveu (sexta, 3/05/2024 à(s)
20:54):

**Comment by RyanMetcalfeInt8** [comment] 2024-05-03 22:09
Hi @fermarper,

In your case does it fail on CPU as well? Just to note, that the failure signature in your case looked a little bit different than the one that @The3IC reported here.

Thanks,
Ryan

**Comment by fermarper** [comment] 2024-05-03 22:29
Choosing CPU works well.
Thanks
Fernando

Ryan Metcalfe ***@***.***> escreveu (sexta, 3/05/2024 à(s)
23:09):

**Comment by RyanMetcalfeInt8** [comment] 2024-05-03 22:34
> Choosing CPU works well. Thanks Fernando 

Okay good. I think issues with your GPU are simply because NVidia devices aren't well supported by the OpenVINO framework... but again, glad to hear that CPU is now giving accurate results.

**Comment by fermarper** [comment] 2024-05-04 00:03
YES
Very thanks for you help Ryan
Hug

Ryan Metcalfe ***@***.***> escreveu (sexta, 3/05/2024 à(s)
23:34):

**Comment by The3IC** [comment] 2024-05-04 12:37
Hi @RyanMetcalfeInt8. Yes, seems the problem was solved, great! 
Tested Finnish, but transcript and translation seemed to work using the on-chip GPU.
As far as I'm converned, you can close this.

btw, the installer is nice in the it does not remove models on the computer.

**Comment by RyanMetcalfeInt8** [comment] 2024-05-05 14:57
Thanks! Closing this one.

**Closed by RyanMetcalfeInt8** 2024-05-05 14:57 UTC
